BaseLoot:
  name: Лут
  interface: true
  # inherit: BaseLoot # Опциональное наследование конфигурации.
  # maps: # попадание хотя бы под одну группу разрешает тип
  # gamemodes: # не определенный тип снимает все ограничения
  # items: