
- name: Факел
  type: default
  category: Light
  required:
    force_visible: true
    skills: { engineering: 1 }
    components:
      - class: WoodenDebris6
        count: 1
        check_type_of: false
      - class: [Bandage,Rag]
        count: 1
        check_type_of: false
        hp: 50%
  failed:
    enable: true # порча предметов при недостаточном навыке.
    item: WoodenDebris2
    count: {min: 3, max: 6} # может быть диапазоном -> count: {min: 1, max: 4}
  result:
    class: TorchDisabled
    modifiers: null

- name: Деревянная ограда
  type: building
  category: Building
  required:
    #skills: { engineering: 1 }
    components:
      - class: WoodenDebris(1-5)
        count: 4
        check_type_of: false
  result:
    class: WoodenSmallFence

- type: system
  required:
    components:
      - class: IFoodItem
        count: 1
  result:
    class: Bread
    count: 1

- type: interact
  required:
    components:
      hand_item: 
        class: Knife
      target:
        class: IFoodItem
  result:
    class: Svetlolik
