
name: All build

on:
  push:
    branches:
      - main
    paths:
      - Src/client/**
      - Src/host/**
      - Src/ReBridge/**
      - Src/Scripts/**
      - Src/Scripts/*.sqf
      - Src/Scripts/*.cpp
      - Src/Scripts/SETTINGS.h
  workflow_dispatch:

jobs:
  allbuild:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        build_type:
          - client
          - client-debug
          - server
          - server-debug
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
      - uses: actions/checkout@v3
      - name: Validate ${{ matrix.build_type }}
        continue-on-error: true
        run: | 
          echo "::group::VM validate"
          Third-party/BuildTools/Validate.bat ${{ matrix.build_type }}
          echo "::endgroup::"
        working-directory: ${{ github.workspace }}
      - name: Post validate ${{ matrix.build_type }}
        run: | 
          python -V
          echo "::group::Python validate"
          python Third-party/BuildTools/parse_output.py ./Third-party/BuildTools/output.txt ./
          echo "::endgroup::"
        working-directory: ${{ github.workspace }}
  updateversion:
    if: github.event_name != 'workflow_dispatch'
    name: Update build number
    runs-on: windows-latest
    needs:
      - allbuild
    steps:
      - uses: actions/checkout@v3
      - name: Increment build number
        id: new_version  
        shell: powershell
        run: |
          echo Workspace is ${{github.workspace}}
          Third-party/BuildTools/update_version.exe path:.\ updpath
          $version = Get-Content .\src\VERSION
          Write-Host "Now version is: $version"
          echo "version_value=${version}" >> $env:GITHUB_OUTPUT
          
      - name: Push changes
        uses: test-room-7/action-update-file@v1  
        if: steps.new_version.outputs.version_value && github.repository == 'Relicta-Team/ReSDK_A3.vr'
        with:
          committer-name: Autoupdater
          file-path: |
            Src/VERSION
            Src/version.hpp
          commit-msg: Update - ${{steps.new_version.outputs.version_value}}
          github-token: ${{secrets.TOKEN}}
