name: Fork Run Tests

on:
  push:

env:
  rb_dir: ${{github.workspace}}/RBuilder/
  rb_exe: ${{github.workspace}}/RBuilder/rb.exe
  rb_args_init: -init build -l

jobs:
  build:
    name: Test
    runs-on: windows-2019
    if: github.repository_owner != 'Relicta-Team'
    strategy:
      fail-fast: true
      matrix:
          flags:
            - -d TEST_ALL -d DEBUG
            - -d TEST_ALL -d RELEASE
    steps:
      - uses: actions/checkout@v3
      - name: Cache Choco
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\choco-cache
          key: ${{ runner.os }}-choco-temp-cache
      - name: Setup msvc+directx
        run: |
          choco config set cacheLocation "${{ github.workspace }}\choco-cache"
          choco install directx
          choco install vcredist2010
          choco install vcredist2012
      - name: Init
        working-directory: ${{env.rb_dir}}
        run: ${{env.rb_exe}} ${{env.rb_args_init}}

      - name: Run
        id: rb_run
        working-directory: ${{env.rb_dir}}
        run: ${{ env.rb_exe }} run ${{ matrix.flags }}
      