name: Fork Run Tests

on:
  push:

env:
  rb_dir: ${{github.workspace}}/RBuilder/
  rb_exe: ${{github.workspace}}/RBuilder/rb.exe
  rb_args_init: -init build -l

jobs:
  build:
    name: Test
    runs-on: windows-2019
    # define LOCAL_BUILD in you repo to enable local build
    if: github.repository_owner != 'Relicta-Team' && vars.LOCAL_BUILD != ''
    strategy:
      fail-fast: true
      matrix:
          flags:
            - -d TEST_ALL -d DEBUG
            - -d TEST_ALL -d RELEASE
    steps:
      - name: Setup msvc+directx
        run: |
          echo skip
        
      - uses: actions/checkout@v3
      - name: Init
        working-directory: ${{env.rb_dir}}
        run: ${{env.rb_exe}} ${{env.rb_args_init}}

      - name: Run
        id: rb_run
        working-directory: ${{env.rb_dir}}
        run: ${{ env.rb_exe }} run ${{ matrix.flags }}

      - name: Export Event Logs
        if: failure()
        run: |
          echo "Exporting Windows event logs..."
          Get-EventLog -LogName Application -Newest 100 | Out-File -FilePath event_logs.txt
          Get-EventLog -LogName System -Newest 100 | Out-File -Append event_logs.txt

      - name: Upload Event Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: event-logs
          path: event_logs.txt
