
name: Deploy ReNode

on:
  push:
    branches:
      - main
      - RBuilder
  workflow_dispatch:

env:
  renode_deploy_path: Third-party/ReNodeDeploy/main.py
  renode_deploy_temp_path: Third-party/ReNodeDeploy/TEMP/RENODE_TEMP/
  RENODE_DEPLOY_TOKEN: ${{secrets.TOKEN}}

jobs:


  deploy:
    name: Main
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
      - uses: actions/checkout@v3
      - name: Deploy ReNode
        working-directory: ${{ github.workspace }}/Third-party/ReNodeDeploy
        run: |
          python -V
          python main.py ./../../ReNode
      - uses: actions/upload-artifact@v4
        with:
          name: ReNode
          path: |
            ${{ env.renode_deploy_temp_path }}
      # - name: Update ReNode application
      #   uses: test-room-7/action-update-file@v1
      #   with:
      #     committer-name: Docgen
      #     file-path: |
      #       ReNode/**
      #     commit-msg: Update ReNode
      #     github-token: ${{secrets.TOKEN}}

